[window]
decorations = "Buttonless"
padding = { x = 4, y = 4}
dynamic_title = true
dynamic_padding = true
resize_increments = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 14

