#! /bin/sh

export _JAVA_AWT_WM_NONREPARENTING=1

wmname LG3D

pgrep -x sxhkd > /dev/null || sxhkd &
sh ~/scripts/wallpaper.sh &
#sh ~/scripts/livewallpaper.sh &
sh ~/.config/polybar/launch.sh &
picom --config ~/.config/picom/config &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            0
bspc config window_gap              15
bspc config focus_follows_pointer   true
bspc config click_to_focus          true
bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc rule -a jetbrains-webstorm     desktop='^1'    follow=off
bspc rule -a Vivaldi-stable         desktop='^2'    follow=off
bspc rule -a Alacritty              desktop='^3'    follow=off
bspc rule -a TelegramDesktop        desktop='^4'    follow=off
bspc rule -a Slack                  desktop='^4'    follow=off
bspc rule -a Inkscape               desktop='^5'    follow=off
bspc rule -a Chromium               desktop='^6'    follow=off
bspc rule -a Google-chrome          dekstop='^6'    follow=off
bspc rule -a obs                    desktop='^7'    follow=off
bspc rule -a Pavucontrol            state=floating  center=on   sticky=on
bspc rule -a Lxappearance           state=floating  center=on   sticky=on
bspc rule -a Bitwarden              state=floating  center=on   sticky=on
bspc rule -a Gnome-disks            state=floating  center=on   sticky=off
bspc rule -a Nvidia-settings        state=floating  center=on   sticky=off
bspc rule -a mpv                    state=floating  center=off  sticky=on
bspc rule -a pop-up                 state=floating  center=on

sh $HOME/.config/bspwm/autostart.sh &

xsetroot -cursor_name left_ptr &
