# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ 
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = { 
      availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
      kernelModules = [ ];
    };
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = { 
      device = "/dev/disk/by-uuid/3828e85e-dd9e-41e0-89fb-0d6ac399776f";
      fsType = "ext4";
    };
    "/boot" = { 
      device = "/dev/disk/by-uuid/3139-5555";
      fsType = "vfat";
    };
    "/data" = { 
      device = "/dev/disk/by-uuid/7dd06070-df62-4043-84b7-46810376622a";
      fsType = "ext4";
    };
    "/home" = { 
      device = "/dev/disk/by-uuid/eea7f185-d4de-47d2-b153-a09cf22fd241";
      fsType = "ext4";
    };
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/9c2fa9d4-33f1-4ef2-9378-21723c71e0ff"; } ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  sound.enable = true;

  hardware = {
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    opengl = {
      enable = true;
      extraPackages = with pkgs; [
        vaapiIntel
        libvdpau-va-gl
        vaapiVdpau
      ];
    };
    pulseaudio = with pkgs; {
      enable = true;
      package = pulseaudioFull;
      support32Bit = true;
    };
  }; 
}
