#! /bin/sh

wmname LG3D

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 0
bspc config window_gap 15
bspc config focus_follows_pointer false
bspc config click_to_focus true
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a jetbrains-webstorm desktop='^1' follow=off
bspc rule -a jetbrains-studio desktop='^1' follow=off
bspc rule -a jetbrains-idea desktop='^1' follow=off
bspc rule -a Code desktop='^1' follow=off
bspc rule -a Code\ -\ Insiders desktop='^1' follow=off
bspc rule -a Emacs desktop="^1" follow=off state=tiled
bspc rule -a Brave-browser desktop='^2' follow=off
bpsc rule -a firefox desktop='^2' follow=off
bspc rule -a TelegramDesktop desktop='^4' follow=off
bspc rule -a Slack desktop='^4' follow=off
bspc rule -a discord desktop='^4' follow=off
bspc rule -a Albion-Online desktop='^6' follow=off state=tiled sticky=off
bspc rule -a obs desktop='^10' follow=off
bspc rule -a Pavucontrol state=floating center=on sticky=on
bspc rule -a Lxappearance state=floating center=on sticky=on
bspc rule -a Bitwarden state=floating center=on sticky=on
bspc rule -a Gnome-disks state=floating center=on sticky=off
bspc rule -a Nvidia-settings state=floating center=on sticky=off
bspc rule -a mpv state=floating center=off sticky=on
bspc rule -a pop-up state=floating center=on
bspc rule -a Gsmartcontrol state=floating center=on
bspc rule -a Windscribe2 state=floating center=on
bspc rule -a Gnome-calculator state=floating center=on
bspc rule -a flameshot state=floating center=on
bspc rule -a Com.github.alainm23.planner state=floating center=on
bspc rule -a SimpleScreenRecorder state=floating center=on
bspc rule -a Space-invaders state=floating center=on
bspc rule -a VirtualBox\ Manager state=floating
bspc rule -a Protonvpn state=floating
bspc rule -a calculator state=floating

# Racket rules
bspc rule -a DrRacket desktop="^1" follow=off
bspc rule -a DrRacket:*:Preferences state=floating center=on
bspc rule -a DrRacket:*:Package\ Manager state=floating center=on
bspc rule -a DrRacket:*:Space\ Invaders state=floating center=on
bspc rule -a DrRacket:*:Sudoku state=floating center=on follow=off

# Nand2tetris tools
bspc rule -a VMEmulatorMain state=floating center=on follow=off

sh ~/.config/polybar/launch.sh
