#!/usr/bin/env python

from os import getcwd, mkdir, path
import sys
import yaml
import requests
from tqdm import tqdm

curr = getcwd()

try:
    with open(sys.argv[1], "r") as f:
        m = yaml.safe_load(f)
        for k, v in m.items():
            print(k)
            if not path.exists(k):
                mkdir(k)
            if v:
                for i, j in v.items():
                    name = str(i).replace("/", "_")
                    print(name)

                    # Download subtitles
                    subp = path.join(curr, k, f"{name}.vtt")
                    r = requests.head(j["sub"])
                    subrs = r.headers["Content-Length"]
                    subs = path.getsize(subp) if path.exists(subp) else 0
                    if int(subs) != int(subrs):
                        r = requests.get(
                            j["sub"], stream=True, headers={"Range": f"bytes={subs}-"}
                        )
                        if r.status_code >= 200 and r.status_code < 300:
                            with tqdm.wrapattr(
                                open(subp, "ab"),
                                "write",
                                unit="B",
                                unit_scale=True,
                                unit_divisor=1024,
                                miniters=1,
                                desc="subtitles",
                                total=int(subrs) - int(subs),
                            ) as f:
                                for chunk in r.iter_content(chunk_size=1024):
                                    f.write(chunk)
                    # Download video
                    vidp = path.join(curr, k, f"{name}.mp4")
                    r = requests.head(j["vid"])
                    vidrs = r.headers["Content-Length"]
                    vids = path.getsize(vidp) if path.exists(vidp) else 0
                    if int(vids) != int(vidrs):
                        r = requests.get(
                            j["vid"], stream=True, headers={"Range": f"bytes={vids}-"}
                        )
                        if r.status_code >= 200 and r.status_code < 300:
                            with tqdm.wrapattr(
                                open(vidp, "ab"),
                                "write",
                                unit="B",
                                unit_scale=True,
                                unit_divisor=1024,
                                miniters=1,
                                desc="video",
                                total=int(vidrs) - int(vids),
                            ) as f:
                                for chunk in r.iter_content(chunk_size=1024):
                                    f.write(chunk)

                    print()

except KeyboardInterrupt:
    # quit
    sys.exit()
